allo: src/alloc/bpool_gtest.cpp File Reference
bpool_gtest.cpp File Reference
#include <gtest/gtest.h>
#include "memuse.hpp"
#include "bpool.hpp"
Functions
TEST (alloc_unit_tests, bpool_first)
TEST (alloc_unit_tests, bpool_last)
Function Documentation
TEST() [1/2]
TEST (alloc_unit_tests , bpool_first)
Definition at line 6 of file bpool_gtest.cpp.
{
    alloc::bpool<int, 4> bp(alloc::placement_policy::first);
    [[maybe_unused]] int *i = bp.allocate(1);
    EXPECT_STREQ(bp.repr().c_str(), "___*");
    [[maybe_unused]] int *j = bp.allocate(1);
    EXPECT_STREQ(bp.repr().c_str(), "__**");
    [[maybe_unused]] int *k = bp.allocate(1);
    EXPECT_STREQ(bp.repr().c_str(), "_***");
    bp.deallocate(i, 1);
    EXPECT_STREQ(bp.repr().c_str(), "_**_");
    i = bp.allocate(1);
    EXPECT_STREQ(bp.repr().c_str(), "_***");
    bp.deallocate(j, 1);
    EXPECT_STREQ(bp.repr().c_str(), "_*_*");
    j = bp.allocate(1);
    EXPECT_STREQ(bp.repr().c_str(), "_***");
}
References alloc::bpool< T, N >::allocate(), alloc::bpool< T, N >::deallocate(), alloc::first, and alloc::bpool< T, N >::repr().
TEST() [2/2]
TEST (alloc_unit_tests , bpool_last)
Definition at line 24 of file bpool_gtest.cpp.
{
    alloc::bpool<int, 4> bp(alloc::placement_policy::last);
    [[maybe_unused]] int *i = bp.allocate(1);
    EXPECT_STREQ(bp.repr().c_str(), "___*");
    [[maybe_unused]] int *j = bp.allocate(1);
    EXPECT_STREQ(bp.repr().c_str(), "__**");
    bp.deallocate(i, 1);
    EXPECT_STREQ(bp.repr().c_str(), "__*_");
    [[maybe_unused]] int *k = bp.allocate(1);
    EXPECT_STREQ(bp.repr().c_str(), "_**_");
    bp.allocate(1);
    EXPECT_STREQ(bp.repr().c_str(), "***_");
    [[maybe_unused]] int *out = bp.allocate(1);
    EXPECT_STREQ(bp.repr().c_str(), "***_");
    EXPECT_TRUE(out == nullptr);
}
References alloc::bpool< T, N >::allocate(), alloc::bpool< T, N >::deallocate(), alloc::last, and alloc::bpool< T, N >::repr().