allo: src/cont/slist_gtest.cpp File Reference
slist_gtest.cpp File Reference
#include <iostream>
#include <sstream>
#include <numeric>
#include <gtest/gtest.h>
#include "alloc/bpool_alloc.hpp"
#include "slist.hpp"
Functions
TEST (cont_unit_tests, slist_push)
TEST (cont_unit_tests, slist_bpool_push)
TEST (cont_unit_tests, slist_bpool_hw3_p1)
TEST (cont_unit_tests, slist_bpool_hw3_p2)
Function Documentation
TEST() [1/4]
TEST (cont_unit_tests , slist_bpool_hw3_p1)
Definition at line 34 of file slist_gtest.cpp.
{
  slist<int> sl(10);
  std::iota(sl.begin(), sl.end(), 0);
  std::stringstream ss;
  std::copy(sl.begin(), sl.end(), std::ostream_iterator<int>(ss, " "));
  EXPECT_EQ(ss.str(), "0 1 2 3 4 5 6 7 8 9 ");
}
References cont::slist< T, Allocator >::begin(), and cont::slist< T, Allocator >::end().
TEST() [2/4]
TEST (cont_unit_tests , slist_bpool_hw3_p2)
Definition at line 42 of file slist_gtest.cpp.
{
  slist<int, alloc::bpool_alloc<int, 10>> sl(10);
  std::iota(sl.begin(), sl.end(), 0);
  std::stringstream ss;
  std::copy(sl.begin(), sl.end(), std::ostream_iterator<int>(ss, " "));
  EXPECT_EQ(ss.str(), "0 1 2 3 4 5 6 7 8 9 ");
}
References cont::slist< T, Allocator >::begin(), and cont::slist< T, Allocator >::end().
TEST() [3/4]
TEST (cont_unit_tests , slist_bpool_push)
Definition at line 22 of file slist_gtest.cpp.
{
  // std::set_terminate(&my_terminate_handler);
  slist<int, alloc::bpool_alloc<int, 10>> sl;
  sl.push_back(10);
  sl.push_back(20);
  sl.push_front(30);
  sl.push_front(40);
  std::stringstream ss;
  std::copy(sl.begin(), sl.end(), std::ostream_iterator<int>(ss, "-"));
  EXPECT_EQ(ss.str(), "40-30-10-20-");
}
References cont::slist< T, Allocator >::begin(), cont::slist< T, Allocator >::end(), cont::slist< T, Allocator >::push_back(), and cont::slist< T, Allocator >::push_front().
TEST() [4/4]
TEST (cont_unit_tests , slist_push)
Definition at line 11 of file slist_gtest.cpp.
{
  slist<int> sl;
  sl.push_back(10);
  sl.push_back(20);
  sl.push_front(30);
  sl.push_front(40);
  std::stringstream ss;
  std::copy(sl.begin(), sl.end(), std::ostream_iterator<int>(ss, "-"));
  EXPECT_EQ(ss.str(), "40-30-10-20-");
}
References cont::slist< T, Allocator >::begin(), cont::slist< T, Allocator >::end(), cont::slist< T, Allocator >::push_back(), and cont::slist< T, Allocator >::push_front().