allo: alloc::bpool< T, N > Struct Template Reference
alloc::bpool< T, N > Struct Template Reference final
#include <bpool.hpp>
Public Types
using value_t = T
using value_storage_t = std::aligned_storage_t< value_size, value_alignment >
Public Member Functions
~bpool () noexcept override
bpool (placement_policy pp=placement_policy::last)
bpool (const bpool &)=delete
bpool & operator= (const bpool &)=delete
T * allocate (size_t n) override
void deallocate (T *ptr, size_t n) override
bool contains (T *p, size_t n) noexcept override
void set (placement_policy pp) noexcept override
size_t total_count () noexcept override
size_t free_count () noexcept override
bool is_free (size_t n) noexcept override
std::string repr () noexcept override
void reset () noexcept override
Public Member Functions inherited from alloc::bpool_base< T >
virtual ~bpool_base ()
virtual T * allocate (size_t n)=0
virtual void deallocate (T *ptr, size_t n)=0
virtual bool contains (T *p, size_t n) noexcept=0
virtual size_t total_count () noexcept=0
virtual size_t free_count () noexcept=0
virtual bool is_free (size_t n) noexcept=0
virtual void set (placement_policy pp) noexcept=0
virtual std::string repr () noexcept=0
virtual void reset () noexcept=0
Static Public Attributes
static constexpr auto value_size = sizeof(value_t)
static constexpr auto value_alignment = alignof(value_t)
Private Member Functions
size_t _get_index_from_address (T *p) noexcept
std::pair< size_t, std::bitset< N > > _find_placement (size_t n) const noexcept
std::pair< size_t, std::bitset< N > > _find_placement_first (size_t n) const noexcept
std::pair< size_t, std::bitset< N > > _find_placement_last (size_t n) const noexcept
Private Attributes
value_storage_t _pool [N]
std::bitset< N > _free {}
placement_policy _policy
size_t _last_idx = 0
Detailed Description
template<typename T, size_t N = OPTIMAL_BPOOL_SEGMENT_ELEMENTS_COUNT>
struct alloc::bpool< T, N >
Definition at line 46 of file bpool.hpp.
Member Typedef Documentation
value_storage_t
template<typename T , size_t N = OPTIMAL_BPOOL_SEGMENT_ELEMENTS_COUNT> using alloc::bpool< T, N >::value_storage_t = std::aligned_storage_t<value_size, value_alignment>
Definition at line 50 of file bpool.hpp.
value_t
template<typename T , size_t N = OPTIMAL_BPOOL_SEGMENT_ELEMENTS_COUNT> using alloc::bpool< T, N >::value_t = T
Definition at line 47 of file bpool.hpp.
Constructor & Destructor Documentation
~bpool()
template<typename T , size_t N = OPTIMAL_BPOOL_SEGMENT_ELEMENTS_COUNT> alloc::bpool< T, N >::~bpool () inline override noexcept
Definition at line 59 of file bpool.hpp.
{
        // TRACE(__PRETTY_FUNCTION__);
    }
bpool() [1/2]
template<typename T , size_t N = OPTIMAL_BPOOL_SEGMENT_ELEMENTS_COUNT> alloc::bpool< T, N >::bpool (placement_policy pp = placement_policy::last) inline
Definition at line 62 of file bpool.hpp.
                                                     : _policy(pp) {
        // TRACE(__PRETTY_FUNCTION__);
        _free.set();
    }
bpool() [2/2]
template<typename T , size_t N = OPTIMAL_BPOOL_SEGMENT_ELEMENTS_COUNT> alloc::bpool< T, N >::bpool (const bpool< T, N > &) delete
Member Function Documentation
_find_placement()
template<typename T , size_t N = OPTIMAL_BPOOL_SEGMENT_ELEMENTS_COUNT> std::pair< size_t, std::bitset< N > > alloc::bpool< T, N >::_find_placement (size_t n) const inline private noexcept
throw not implemented
Definition at line 97 of file bpool.hpp.
{
        // if constexpr(P == placement_policy::first) - in case of P is part of this type
        switch (_policy) {
            case  placement_policy::first:
                return _find_placement_first(n);
            case  placement_policy::last:
                return _find_placement_last(n);
            default:
                return _find_placement_first(n);
        }
    }
References alloc::first, and alloc::last.
_find_placement_first()
template<typename T , size_t N> std::pair< size_t, std::bitset< N > > alloc::bpool< T, N >::_find_placement_first (size_t n) const private noexcept
Definition at line 164 of file bpool.hpp.
{
    // TRACE(__PRETTY_FUNCTION__);
    for (auto pos = _free._Find_first(); pos <= N - n;){
        if (_details::countr(_free, true, pos, n) >= n)
            return std::make_pair(pos, _details::get_mask<N>(pos, pos + n));
        pos = _free._Find_next(pos);
        // for "big" n
        // if (auto mask = get_mask<size>(pos, pos + n); (_free & mask).count() == n)
        //     return std::make_pair(pos, mask);
    }
    return std::make_pair(N, std::bitset<N>());
}
References alloc::_details::countr().
_find_placement_last()
template<typename T , size_t N> std::pair< size_t, std::bitset< N > > alloc::bpool< T, N >::_find_placement_last (size_t n) const private noexcept
Definition at line 179 of file bpool.hpp.
{
    // TRACE(__PRETTY_FUNCTION__);
    // #include <bit> std::countl_one - only if T is an unsigned integer type...
    // if (size_t i = _details::countl(_free, true, 0); i >= n){
    //     return std::make_pair(N - i, _details::get_mask<N>(N - i, N - i + n));
    if (_last_idx + n <= N){
        return std::make_pair(_last_idx, _details::get_mask<N>(_last_idx, _last_idx + n));
    } else {
        return std::make_pair(N, std::bitset<N>());
    }
}
_get_index_from_address()
template<typename T , size_t N = OPTIMAL_BPOOL_SEGMENT_ELEMENTS_COUNT> size_t alloc::bpool< T, N >::_get_index_from_address (T * p) inline private noexcept
Definition at line 93 of file bpool.hpp.
{
        // TRACE(__PRETTY_FUNCTION__);
        return contains(p, 1) ? p - reinterpret_cast<T*>(&_pool) : N;
    }
References alloc::bpool_base< T >::contains().
allocate()
template<typename T , size_t N> T * alloc::bpool< T, N >::allocate (size_t n) override virtual
Implements alloc::bpool_base< T >.
Definition at line 128 of file bpool.hpp.
{
    // TRACE(__PRETTY_FUNCTION__);
    if (n == 0 || n > free_count())
        return nullptr;
    // todo: add check of max available placement size (if it makes sense... not only for best placament policy)
    if (auto [pos, mask] = _find_placement(n); pos != N){
        if (n == 1)
            _free.reset(pos);
        else
            _free &= mask.flip();
        if (pos + n > _last_idx)
            _last_idx = pos + n;
        // return std::assume_aligned<value_alignment, T>(reinterpret_cast<T*>(&_pool[pos]));
        return reinterpret_cast<T*>(&_pool[pos]);
    } else {
        // return static_cast<T *>(::operator new(value_size));
        return nullptr;
    }
}
References alloc::bpool_base< T >::free_count().
Referenced by TEST(), and TEST().
contains()
template<typename T , size_t N = OPTIMAL_BPOOL_SEGMENT_ELEMENTS_COUNT> bool alloc::bpool< T, N >::contains (T * p, size_t n) inline override virtual noexcept
Implements alloc::bpool_base< T >.
Definition at line 72 of file bpool.hpp.
{
        // TRACE(__PRETTY_FUNCTION__);
        T* from = reinterpret_cast<T*>(const_cast<value_storage_t*>(&_pool[0]));
        // std::cout << " contains " << p << " - " << (p + n) << " from " << from  << " to " << from + N << " = " << (bool)((from <= p) && ((p + n) <= (from + N))) << std::endl;
        return (from <= p) && ((p + n) <= (from + N));
    }
deallocate()
template<typename T , size_t N> void alloc::bpool< T, N >::deallocate (T * ptr, size_t n) override virtual
Implements alloc::bpool_base< T >.
Definition at line 149 of file bpool.hpp.
{
    // TRACE(__PRETTY_FUNCTION__);
    if (auto i = _get_index_from_address(p); i != N){ // todo: check i + n > N and throw exception
        if (n == 1)
            _free.set(i);
        else
            _free |= _details::get_mask<N>(i, i + n);
        if (i + n >= _last_idx)
            _last_idx = i;
    } else {
        // ::operator delete(p);
    }
}
Referenced by TEST(), and TEST().
free_count()
template<typename T , size_t N = OPTIMAL_BPOOL_SEGMENT_ELEMENTS_COUNT> size_t alloc::bpool< T, N >::free_count () inline override virtual noexcept
Implements alloc::bpool_base< T >.
Definition at line 82 of file bpool.hpp.
{ return _free.count(); }
is_free()
template<typename T , size_t N = OPTIMAL_BPOOL_SEGMENT_ELEMENTS_COUNT> bool alloc::bpool< T, N >::is_free (size_t n) inline override virtual noexcept
Implements alloc::bpool_base< T >.
Definition at line 83 of file bpool.hpp.
{
        // TRACE(__PRETTY_FUNCTION__);
        [[maybe_unused]] auto [pos, mask] = _find_placement(n);
        return (pos != N);
    }
operator=()
template<typename T , size_t N = OPTIMAL_BPOOL_SEGMENT_ELEMENTS_COUNT> bpool & alloc::bpool< T, N >::operator= (const bpool< T, N > &) delete
repr()
template<typename T , size_t N = OPTIMAL_BPOOL_SEGMENT_ELEMENTS_COUNT> std::string alloc::bpool< T, N >::repr () inline override virtual noexcept
Implements alloc::bpool_base< T >.
Definition at line 89 of file bpool.hpp.
{ return _free.to_string('*', '_'); }
Referenced by TEST(), and TEST().
reset()
template<typename T , size_t N = OPTIMAL_BPOOL_SEGMENT_ELEMENTS_COUNT> void alloc::bpool< T, N >::reset () inline override virtual noexcept
Implements alloc::bpool_base< T >.
Definition at line 91 of file bpool.hpp.
{ _free.reset(); }
set()
template<typename T , size_t N = OPTIMAL_BPOOL_SEGMENT_ELEMENTS_COUNT> void alloc::bpool< T, N >::set (placement_policy pp) inline override virtual noexcept
Implements alloc::bpool_base< T >.
Definition at line 79 of file bpool.hpp.
{ _policy = pp; }
total_count()
template<typename T , size_t N = OPTIMAL_BPOOL_SEGMENT_ELEMENTS_COUNT> size_t alloc::bpool< T, N >::total_count () inline override virtual noexcept
Implements alloc::bpool_base< T >.
Definition at line 81 of file bpool.hpp.
{ return N; }
Member Data Documentation
_free
template<typename T , size_t N = OPTIMAL_BPOOL_SEGMENT_ELEMENTS_COUNT> std::bitset<N> alloc::bpool< T, N >::_free {} private
Definition at line 53 of file bpool.hpp.
_last_idx
template<typename T , size_t N = OPTIMAL_BPOOL_SEGMENT_ELEMENTS_COUNT> size_t alloc::bpool< T, N >::_last_idx = 0 private
Definition at line 56 of file bpool.hpp.
_policy
template<typename T , size_t N = OPTIMAL_BPOOL_SEGMENT_ELEMENTS_COUNT> placement_policy alloc::bpool< T, N >::_policy private
Definition at line 54 of file bpool.hpp.
_pool
template<typename T , size_t N = OPTIMAL_BPOOL_SEGMENT_ELEMENTS_COUNT> value_storage_t alloc::bpool< T, N >::_pool[N] private
Definition at line 52 of file bpool.hpp.
value_alignment
template<typename T , size_t N = OPTIMAL_BPOOL_SEGMENT_ELEMENTS_COUNT> constexpr auto alloc::bpool< T, N >::value_alignment = alignof(value_t) static constexpr
Definition at line 49 of file bpool.hpp.
value_size
template<typename T , size_t N = OPTIMAL_BPOOL_SEGMENT_ELEMENTS_COUNT> constexpr auto alloc::bpool< T, N >::value_size = sizeof(value_t) static constexpr
Definition at line 48 of file bpool.hpp.
The documentation for this struct was generated from the following file:
src/alloc/bpool.hpp