allo: cont::slist< T, Allocator > Struct Template Reference
cont::slist< T, Allocator > Struct Template Reference
#include <slist.hpp>
Public Types
using value_type = T
using reference = value_type &
using const_reference = value_type const &
using difference_type = ptrdiff_t
using size_type = size_t
using allocator_type = Allocator
using iterator = slist_details::iterator< value_type >
using const_iterator = slist_details::const_iterator< value_type >
using alloc_traits = allocator_traits< allocator_type >
Public Member Functions
slist (node_allocator_type &&a={})
slist (allocator_type &&a)
slist (const slist &other)
slist (const slist &other, allocator_type a)
slist (slist &&other) noexcept
slist (slist &&other, allocator_type a)
slist (size_t size)
~slist ()
slist & operator= (const slist &other)
slist & operator= (slist &&other)
void swap (slist &other) noexcept
size_t size () const noexcept
bool empty () const noexcept
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
const_iterator cbegin () const
const_iterator cend () const
T & front ()
T const & front () const
template<typename... Args>
iterator emplace (iterator i, Args &&... args)
template<typename... Args>
void emplace_front (Args &&... args)
template<typename... Args>
void emplace_back (Args &&... args)
iterator insert (iterator i, const T &v)
void push_front (const T &v)
void push_back (const T &v)
iterator erase (iterator b, iterator e)
iterator erase (iterator i)
void pop_front ()
allocator_type get_allocator () &&
node_allocator_type & get_node_allocator () &
Private Types
using node_base = slist_details::node_base< value_type >
using node = slist_details::node< value_type >
using node_allocator_type = typename alloc_traits::template rebind_alloc< node >
using node_alloc_traits = allocator_traits< node_allocator_type >
Private Attributes
node_base head_
node_base * ptail_
size_t size_
node_allocator_type node_alloc_
Detailed Description
template<typename T, typename Allocator = std::allocator<std::remove_cv_t<T>>>
struct cont::slist< T, Allocator >
Definition at line 125 of file slist.hpp.
Member Typedef Documentation
alloc_traits
template<typename T , typename Allocator = std::allocator<std::remove_cv_t<T>>> using cont::slist< T, Allocator >::alloc_traits = allocator_traits<allocator_type>
Definition at line 134 of file slist.hpp.
allocator_type
template<typename T , typename Allocator = std::allocator<std::remove_cv_t<T>>> using cont::slist< T, Allocator >::allocator_type = Allocator
Definition at line 131 of file slist.hpp.
const_iterator
template<typename T , typename Allocator = std::allocator<std::remove_cv_t<T>>> using cont::slist< T, Allocator >::const_iterator = slist_details::const_iterator<value_type>
Definition at line 133 of file slist.hpp.
const_reference
template<typename T , typename Allocator = std::allocator<std::remove_cv_t<T>>> using cont::slist< T, Allocator >::const_reference = value_type const &
Definition at line 128 of file slist.hpp.
difference_type
template<typename T , typename Allocator = std::allocator<std::remove_cv_t<T>>> using cont::slist< T, Allocator >::difference_type = ptrdiff_t
Definition at line 129 of file slist.hpp.
iterator
template<typename T , typename Allocator = std::allocator<std::remove_cv_t<T>>> using cont::slist< T, Allocator >::iterator = slist_details::iterator<value_type>
Definition at line 132 of file slist.hpp.
node
template<typename T , typename Allocator = std::allocator<std::remove_cv_t<T>>> using cont::slist< T, Allocator >::node = slist_details::node<value_type> private
Definition at line 137 of file slist.hpp.
node_alloc_traits
template<typename T , typename Allocator = std::allocator<std::remove_cv_t<T>>> using cont::slist< T, Allocator >::node_alloc_traits = allocator_traits<node_allocator_type> private
Definition at line 139 of file slist.hpp.
node_allocator_type
template<typename T , typename Allocator = std::allocator<std::remove_cv_t<T>>> using cont::slist< T, Allocator >::node_allocator_type = typename alloc_traits::template rebind_alloc<node> private
Definition at line 138 of file slist.hpp.
node_base
template<typename T , typename Allocator = std::allocator<std::remove_cv_t<T>>> using cont::slist< T, Allocator >::node_base = slist_details::node_base<value_type> private
Definition at line 136 of file slist.hpp.
reference
template<typename T , typename Allocator = std::allocator<std::remove_cv_t<T>>> using cont::slist< T, Allocator >::reference = value_type &
Definition at line 127 of file slist.hpp.
size_type
template<typename T , typename Allocator = std::allocator<std::remove_cv_t<T>>> using cont::slist< T, Allocator >::size_type = size_t
Definition at line 130 of file slist.hpp.
value_type
template<typename T , typename Allocator = std::allocator<std::remove_cv_t<T>>> using cont::slist< T, Allocator >::value_type = T
Definition at line 126 of file slist.hpp.
Constructor & Destructor Documentation
slist() [1/7]
template<typename T , typename Allocator = std::allocator<std::remove_cv_t<T>>> cont::slist< T, Allocator >::slist (node_allocator_type && a = {}) inline
Definition at line 147 of file slist.hpp.
                                  {}) : head_(), ptail_(&head_), size_(0), node_alloc_(std::forward<node_allocator_type>(a)) {
    // TRACE("call [%s] with a as [%s]", __PRETTY_FUNCTION__, boost::typeindex::type_id_runtime(a));
  }
slist() [2/7]
template<typename T , typename Allocator = std::allocator<std::remove_cv_t<T>>> cont::slist< T, Allocator >::slist (allocator_type && a) inline
Definition at line 150 of file slist.hpp.
                            : slist(node_alloc_type(std::forward<allocator_type>(a))) {
    // TRACE("call [%s] with a as [%s]", __PRETTY_FUNCTION__, boost::typeindex::type_id_runtime(a));
  }
slist() [3/7]
template<typename T , typename Allocator = std::allocator<std::remove_cv_t<T>>> cont::slist< T, Allocator >::slist (const slist< T, Allocator > & other) inline
Definition at line 159 of file slist.hpp.
                           : slist(other.get_allocator()) {
    // TRACE("call [%s] with other as [%s]", __PRETTY_FUNCTION__, boost::typeindex::type_id_runtime(other));
    operator=(other);
  }
References cont::slist< T, Allocator >::operator=().
slist() [4/7]
template<typename T , typename Allocator = std::allocator<std::remove_cv_t<T>>> cont::slist< T, Allocator >::slist (const slist< T, Allocator > & other, allocator_type a) inline
Definition at line 163 of file slist.hpp.
                                             : slist(a) {
    // TRACE("call [%s] with other as [%s]", __PRETTY_FUNCTION__, boost::typeindex::type_id_runtime(other));
    operator=(other);
  }
References cont::slist< T, Allocator >::operator=().
slist() [5/7]
template<typename T , typename Allocator = std::allocator<std::remove_cv_t<T>>> cont::slist< T, Allocator >::slist (slist< T, Allocator > && other) inline noexcept
Definition at line 168 of file slist.hpp.
                                : slist(other.get_allocator()) {
    // TRACE("call [%s] with other as [%s]", __PRETTY_FUNCTION__, boost::typeindex::type_id_runtime(other));
    head_ = move(other.head_);
    ptail_ = move(other.ptail_);
  }
References cont::slist< T, Allocator >::head_, and cont::slist< T, Allocator >::ptail_.
slist() [6/7]
template<typename T , typename Allocator = std::allocator<std::remove_cv_t<T>>> cont::slist< T, Allocator >::slist (slist< T, Allocator > && other, allocator_type a) inline
Definition at line 173 of file slist.hpp.
                                        : slist(a) {
    // TRACE("call [%s] with other as [%s]", __PRETTY_FUNCTION__, boost::typeindex::type_id_runtime(other));
    operator=(move(other));
  }
References cont::slist< T, Allocator >::operator=().
slist() [7/7]
template<typename T , typename Allocator = std::allocator<std::remove_cv_t<T>>> cont::slist< T, Allocator >::slist (size_t size) inline
Definition at line 177 of file slist.hpp.
                    : slist(){
    // TRACE(__PRETTY_FUNCTION__);
    while(size--)
      push_front(T{});
  }
References cont::slist< T, Allocator >::push_front(), and cont::slist< T, Allocator >::size().
~slist()
template<typename T , typename Allocator = std::allocator<std::remove_cv_t<T>>> cont::slist< T, Allocator >::~slist () inline
Definition at line 182 of file slist.hpp.
           {
    // TRACE(__PRETTY_FUNCTION__);
    erase(begin(), end());
  }
References cont::slist< T, Allocator >::begin(), cont::slist< T, Allocator >::end(), and cont::slist< T, Allocator >::erase().
Member Function Documentation
begin() [1/2]
template<typename T , typename Allocator = std::allocator<std::remove_cv_t<T>>> iterator cont::slist< T, Allocator >::begin () inline
Definition at line 196 of file slist.hpp.
{ return iterator(&head_); }
References cont::slist< T, Allocator >::head_.
Referenced by cont::slist< T, Allocator >::emplace_front(), main(), cont::operator==(), cont::slist< T, Allocator >::pop_front(), cont::slist< T, Allocator >::push_front(), TEST(), TEST(), TEST(), TEST(), and cont::slist< T, Allocator >::~slist().
begin() [2/2]
template<typename T , typename Allocator = std::allocator<std::remove_cv_t<T>>> const_iterator cont::slist< T, Allocator >::begin () const inline
Definition at line 198 of file slist.hpp.
{ return const_iterator(&head_); }
References cont::slist< T, Allocator >::head_.
cbegin()
template<typename T , typename Allocator = std::allocator<std::remove_cv_t<T>>> const_iterator cont::slist< T, Allocator >::cbegin () const inline
Definition at line 200 of file slist.hpp.
{ return const_iterator(&head_); }
References cont::slist< T, Allocator >::head_.
cend()
template<typename T , typename Allocator = std::allocator<std::remove_cv_t<T>>> const_iterator cont::slist< T, Allocator >::cend () const inline
Definition at line 201 of file slist.hpp.
{ return const_iterator(ptail_); }
References cont::slist< T, Allocator >::ptail_.
emplace()
template<typename T , typename A > template<typename... Args> slist< T, A >::iterator cont::slist< T, A >::emplace (iterator i, Args &&... args)
Definition at line 283 of file slist.hpp.
{
  // TRACE(__PRETTY_FUNCTION__);
  // node *new_node = node_alloc_.allocate(); // static_cast<node *>(...)
  node *new_node = node_alloc_traits::allocate(node_alloc_, 1);
  try {
/*
  Allocator-aware containers always call std::allocator_traits<A>::construct(m, p, args)
  to construct an object of type T at p using args, with m == get_allocator().
  The default construct in std::allocator calls ::new((void*)p) T(args) (until C++20)
  std::allocator has no construct member and std::construct_at(p, args) is called when constructing elements (since C++20),
  but specialized allocators may choose a different definition
*/
    // node_alloc_traits::construct(node_alloc_, addressof(new_node->value_), forward<Args>(args)...);
    std::construct_at(addressof(new_node->value_), forward<Args>(args)...);
  } catch (...) {
    // Recover resources if exception on constructor call.
    // node_alloc_.deallocate(new_node);
    node_alloc_traits::deallocate(node_alloc_, new_node, 1);
    // node_alloc_.deallocate(new_node, 1);
    throw;
  }
  new_node->next_ = it.prev_->next_;
  it.prev_->next_ = new_node;
  if (it.prev_ == ptail_)
    ptail_ = new_node; // Added at end
  ++size_;
  return it;
}
References cont::slist_details::node_base< Tp >::next_, cont::slist_details::const_iterator< Tp >::prev_, and cont::slist_details::node< Tp >::value_.
Referenced by cont::slist< T, Allocator >::emplace_back(), cont::slist< T, Allocator >::emplace_front(), cont::slist< T, Allocator >::insert(), cont::slist< T, Allocator >::push_back(), and cont::slist< T, Allocator >::push_front().
emplace_back()
template<typename T , typename Allocator = std::allocator<std::remove_cv_t<T>>> template<typename... Args> void cont::slist< T, Allocator >::emplace_back (Args &&... args) inline
Definition at line 210 of file slist.hpp.
{
    emplace(end(), forward<Args>(args)...);
  }
References cont::slist< T, Allocator >::emplace(), and cont::slist< T, Allocator >::end().
emplace_front()
template<typename T , typename Allocator = std::allocator<std::remove_cv_t<T>>> template<typename... Args> void cont::slist< T, Allocator >::emplace_front (Args &&... args) inline
Definition at line 207 of file slist.hpp.
{
    emplace(begin(), forward<Args>(args)...);
  }
References cont::slist< T, Allocator >::begin(), and cont::slist< T, Allocator >::emplace().
empty()
template<typename T , typename Allocator = std::allocator<std::remove_cv_t<T>>> bool cont::slist< T, Allocator >::empty () const inline noexcept
Definition at line 194 of file slist.hpp.
{ return 0 == size_; }
References cont::slist< T, Allocator >::size_.
end() [1/2]
template<typename T , typename Allocator = std::allocator<std::remove_cv_t<T>>> iterator cont::slist< T, Allocator >::end () inline
Definition at line 197 of file slist.hpp.
{ return iterator(ptail_); }
References cont::slist< T, Allocator >::ptail_.
Referenced by cont::slist< T, Allocator >::emplace_back(), main(), cont::operator==(), cont::slist< T, Allocator >::push_back(), TEST(), TEST(), TEST(), TEST(), and cont::slist< T, Allocator >::~slist().
end() [2/2]
template<typename T , typename Allocator = std::allocator<std::remove_cv_t<T>>> const_iterator cont::slist< T, Allocator >::end () const inline
Definition at line 199 of file slist.hpp.
{ return const_iterator(ptail_); }
References cont::slist< T, Allocator >::ptail_.
erase() [1/2]
template<typename T , typename A > slist< T, A >::iterator cont::slist< T, A >::erase (iterator b, iterator e)
Definition at line 313 of file slist.hpp.
{
  // TRACE(__PRETTY_FUNCTION__);
  node *erase_next = b.prev_->next_;
  node *erase_past = e.prev_->next_; // one past last erasure
  if (nullptr == erase_past)
    ptail_ = b.prev_;          // Erasing at tail
  b.prev_->next_ = erase_past; // splice out sublist
  while (erase_next != erase_past) {
    node *old_node = erase_next;
    erase_next = erase_next->next_;
    --size_;
    // node_alloc_traits::destroy(node_alloc_, addressof(old_node->value_));
        if constexpr (not std::is_fundamental_v<T>)
        {
      addressof(old_node->value_)->~T();
        }
    node_alloc_traits::deallocate(node_alloc_, old_node, 1);
    // node_alloc_.deallocate(old_node, 1);
  }
  return b;
}
References cont::slist_details::node_base< Tp >::next_, cont::slist_details::const_iterator< Tp >::prev_, and cont::slist_details::node< Tp >::value_.
Referenced by cont::slist< T, Allocator >::erase(), cont::slist< T, Allocator >::pop_front(), and cont::slist< T, Allocator >::~slist().
erase() [2/2]
template<typename T , typename Allocator = std::allocator<std::remove_cv_t<T>>> iterator cont::slist< T, Allocator >::erase (iterator i) inline
Definition at line 220 of file slist.hpp.
{
    iterator e = i;
    return erase(i, ++e);
  }
References cont::slist< T, Allocator >::erase().
front() [1/2]
template<typename T , typename Allocator = std::allocator<std::remove_cv_t<T>>> T & cont::slist< T, Allocator >::front () inline
Definition at line 203 of file slist.hpp.
{ return head_.next_->value_; }
References cont::slist< T, Allocator >::head_, cont::slist_details::node_base< Tp >::next_, and cont::slist_details::node< Tp >::value_.
front() [2/2]
template<typename T , typename Allocator = std::allocator<std::remove_cv_t<T>>> T const & cont::slist< T, Allocator >::front () const inline
Definition at line 204 of file slist.hpp.
{ return head_.next_->value_; }
References cont::slist< T, Allocator >::head_, cont::slist_details::node_base< Tp >::next_, and cont::slist_details::node< Tp >::value_.
get_allocator()
template<typename T , typename Allocator = std::allocator<std::remove_cv_t<T>>> allocator_type cont::slist< T, Allocator >::get_allocator () && inline
Definition at line 227 of file slist.hpp.
{
    // WARNING(__PRETTY_FUNCTION__);
    return allocator_type{};
  }
get_node_allocator()
template<typename T , typename Allocator = std::allocator<std::remove_cv_t<T>>> node_allocator_type & cont::slist< T, Allocator >::get_node_allocator () & inline
Definition at line 231 of file slist.hpp.
{
    // WARNING(__PRETTY_FUNCTION__);
    return node_alloc_;
  }
References cont::slist< T, Allocator >::node_alloc_.
insert()
template<typename T , typename Allocator = std::allocator<std::remove_cv_t<T>>> iterator cont::slist< T, Allocator >::insert (iterator i, const T & v) inline
Definition at line 214 of file slist.hpp.
{ return emplace(i, v); }
References cont::slist< T, Allocator >::emplace().
operator=() [1/2]
template<typename T , typename A > slist< T, A > & cont::slist< T, A >::operator= (const slist< T, Allocator > & other)
Definition at line 249 of file slist.hpp.
{
  if (&other == this)
    return *this;
  erase(begin(), end());
  for (const T &v : other)
    push_back(v);
  return *this;
}
Referenced by cont::slist< T, Allocator >::slist(), cont::slist< T, Allocator >::slist(), and cont::slist< T, Allocator >::slist().
operator=() [2/2]
template<typename T , typename A > slist< T, A > & cont::slist< T, A >::operator= (slist< T, Allocator > && other)
Definition at line 259 of file slist.hpp.
{
  if (&other == this)
    return *this;
  if (node_alloc_ == other.node_alloc_) {
    erase(begin(), end());
    swap(other);
  } else
    operator=(other); // Copy assign
  return *this;
}
pop_front()
template<typename T , typename Allocator = std::allocator<std::remove_cv_t<T>>> void cont::slist< T, Allocator >::pop_front () inline
Definition at line 224 of file slist.hpp.
{ erase(begin()); }
References cont::slist< T, Allocator >::begin(), and cont::slist< T, Allocator >::erase().
push_back()
template<typename T , typename Allocator = std::allocator<std::remove_cv_t<T>>> void cont::slist< T, Allocator >::push_back (const T & v) inline
Definition at line 216 of file slist.hpp.
{ emplace(end(), v); }
References cont::slist< T, Allocator >::emplace(), and cont::slist< T, Allocator >::end().
Referenced by TEST(), and TEST().
push_front()
template<typename T , typename Allocator = std::allocator<std::remove_cv_t<T>>> void cont::slist< T, Allocator >::push_front (const T & v) inline
Definition at line 215 of file slist.hpp.
{ emplace(begin(), v); }
References cont::slist< T, Allocator >::begin(), and cont::slist< T, Allocator >::emplace().
Referenced by cont::slist< T, Allocator >::slist(), TEST(), and TEST().
size()
template<typename T , typename Allocator = std::allocator<std::remove_cv_t<T>>> size_t cont::slist< T, Allocator >::size () const inline noexcept
Definition at line 193 of file slist.hpp.
{ return size_; }
References cont::slist< T, Allocator >::size_.
Referenced by cont::operator==(), and cont::slist< T, Allocator >::slist().
swap()
template<typename T , typename A > void cont::slist< T, A >::swap (slist< T, Allocator > & other) noexcept
Definition at line 271 of file slist.hpp.
{
  assert(node_alloc_ == other.node_alloc_);
  node_base *new_tail = other.empty() ? &head_ : other.ptail_;
  node_base *new_other_tail = empty() ? &other.head_ : ptail_;
  swap(head_.next_, other.head_.next_);
  swap(size_, other.size_);
  ptail_ = new_tail;
  other.ptail_ = new_other_tail;
}
Member Data Documentation
head_
template<typename T , typename Allocator = std::allocator<std::remove_cv_t<T>>> node_base cont::slist< T, Allocator >::head_ private
Definition at line 141 of file slist.hpp.
Referenced by cont::slist< T, Allocator >::begin(), cont::slist< T, Allocator >::begin(), cont::slist< T, Allocator >::cbegin(), cont::slist< T, Allocator >::front(), cont::slist< T, Allocator >::front(), and cont::slist< T, Allocator >::slist().
node_alloc_
template<typename T , typename Allocator = std::allocator<std::remove_cv_t<T>>> node_allocator_type cont::slist< T, Allocator >::node_alloc_ private
Definition at line 144 of file slist.hpp.
Referenced by cont::slist< T, Allocator >::get_node_allocator().
ptail_
template<typename T , typename Allocator = std::allocator<std::remove_cv_t<T>>> node_base* cont::slist< T, Allocator >::ptail_ private
Definition at line 142 of file slist.hpp.
Referenced by cont::slist< T, Allocator >::cend(), cont::slist< T, Allocator >::end(), cont::slist< T, Allocator >::end(), and cont::slist< T, Allocator >::slist().
size_
template<typename T , typename Allocator = std::allocator<std::remove_cv_t<T>>> size_t cont::slist< T, Allocator >::size_ private
Definition at line 143 of file slist.hpp.
Referenced by cont::slist< T, Allocator >::empty(), and cont::slist< T, Allocator >::size().
The documentation for this struct was generated from the following file:
src/cont/slist.hpp